// pages/index.vue
<template>
  <main>
    <bar />
    <banner />
  </main>
</template>

<script lang="ts">
import Vue from 'vue'
import Bar from '~/components/pc/Bar'
import Banner from '~/components/pc/Banner'

export default Vue.extend({
  components: {
    Bar,
    Banner
  },
  async asyncData ({ $content, store: { commit } }) {
    const homepageData: ContentJson = await $content('database/homepage').fetch()
    commit('database/homepage', homepageData.data)
  }
})
</script>

<style lang="scss">
// reset
a {
  color: inherit;
  text-decoration: none;
}
</style>

// asyncData 方法在 .tsx 中没有执行

// import { Vue, Component } from 'vue-property-decorator'
// import Bar from '~/components/pc/Bar'
// import Banner from '~/components/pc/Banner'

// @Component
// export default class PageIndex extends Vue {
//   async asyncData({ $content, store: { commit } }) {
//     console.log(123123123123)
//     const homepageData: ContentJson = await $content('database/homepage').fetch()
//     commit('database/homepage', homepageData.data)
//   }

//   render() {
//     return (
//       <main>
//         <Bar />
//         <Banner />
//       </main>
//     )
//   }
// }

// pages/index.tsx

import { Vue, Component } from 'nuxt-property-decorator'
import Banner from '~/components/pc/Banner'

import './style.scss'

@Component
export default class PageIndex extends Vue {
  async asyncData({ store: { dispatch } }) {
    await Promise.all([
      dispatch('database/bar:get'),
      dispatch('database/homepage:get')
    ])
  }

  layout (context) {
    // TODO 检测移动端时使用 h5
    // const ua: string = context.req.headers['user-agent']
    // const isMobile: boolean = !!ua.toLowerCase().match(/(iphone|ipod|ipad|android)/)
    // 可以尝试通过服务端中间件加入到上下文中
    return 'pc'
  }

  render() {
    return (
      <main>
        <Banner />
      </main>
    )
  }
}
